version: "3.9"

services:
  email-parser:
    image: email-parser:latest
    container_name: email-parser
    environment:
      INGESTION_URL: "http://ingestion:8080/api/ingestion/v1/ingestion/"
    ports:
      - "5000:5000"
