version: "3.9"

services:
  youtube-connector:
    image: youtube-connector:latest
    container_name: youtube-connector
    environment:
      INGESTION_URL: "http://ingestion:8080/api/ingestion/v1/ingestion/"
    ports:
      - "5000:5000"
