version: "3.5"
services:
    keycloak:
        image: quay.io/keycloak/keycloak:12.0.2
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres-keycloak:5432
            DB_DATABASE: keycloak
            DB_USER: openk9
            DB_SCHEMA: public
            DB_PASSWORD: openk9
            KEYCLOAK_USER: openk9
            KEYCLOAK_PASSWORD: openk9
            KK_TO_RMQ_URL: rabbitmq
            KK_TO_RMQ_PORT: 5672
            KK_TO_RMQ_USERNAME: openk9
            KK_TO_RMQ_PASSWORD: openk9
            KK_TO_RMQ_VHOST: /
            KK_TO_RMQ_EXCHANGE: auth.topic
        volumes:
            - ./keycloak/opt/jboss/keycloak/standalone/deployments/:/opt/jboss/keycloak/standalone/deployments/
        ports:
            - 7070:8080
        depends_on:
            - postgres-keycloak
    postgres-keycloak:
        image: postgres:latest
        container_name: postgres-keycloak
        hostname: postgres-keycloak
        environment:
            - POSTGRES_PASSWORD=openk9
            - POSTGRES_USER=openk9
            - POSTGRES_DB=keycloak
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./postgres-keycloak/db-data:/var/lib/postgresql/data
