version: "3.5"
services:
    search-standalone-frontend:
        image: smclab/openk9-search-standalone-frontend:latest
        container_name: search-standalone-frontend
        ports:
            - "8081:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.entrypoints=web"
            - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
    search-admin:
        image: smclab/openk9-admin-ui:latest
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.admin.entrypoints=web"
            - "traefik.http.routers.admin.rule=PathPrefix(`/admin`)"
    admin-logs-service:
        image: smclab/openk9-admin-logs-service:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /bin/docker:/bin/docker
        labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.logs-strip.stripprefix.prefixes=/logs"
            - "traefik.http.routers.logs.entrypoints=web"
            - "traefik.http.routers.logs.rule=PathPrefix(`/logs`)"
            - "traefik.http.routers.logs.middlewares=logs-strip@docker"
            - "traefik.http.routers.traefik.middlewares=traefik-compress"
            - "traefik.http.middlewares.traefik-compress.compress=true"
    reverse-proxy:
        image: traefik:v2.3
        command: --api.insecure=true --providers.docker --providers.docker.exposedbydefault=false --entrypoints.web.address=:80
        networks:
            default:
                aliases:
                    - openk9.io
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - '8888:80'
            - '8182:8080'