version: "3.5"
services:
    index-writer:
        image: openk9-index-writer:latest
        container_name: openk9-index-writer
        command: sh -c "/wait && cp -a /opt/apache-karaf/configs/. /opt/apache-karaf/etc && karaf run debug"
        environment:
            WAIT_HOSTS: elasticsearch:9200, rabbitmq:5672
            WAIT_HOSTS_TIMEOUT: 300
            JAVA_DEBUG_PORT: '*:5005'
        volumes:
            - ./index-writer/configs:/opt/apache-karaf/configs
        expose:
            - "1099"
            - "8080"
            - "44444"
            - "8101"
            - "8181"
            - "5005"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.index-writer-docker.loadbalancer.server.port=8080"
            - "traefik.http.middlewares.index-writer-strip.stripprefix.prefixes=/index-writer"
            - "traefik.http.routers.index-writer.entrypoints=web"
            - "traefik.http.routers.index-writer.rule=PathPrefix(`/index-writer`)"
            - "traefik.http.middlewares.index-writer_compress.compress=true"
            - "traefik.http.middlewares.openk9-forwarded-host.headers.customrequestheaders.X-Forwarded-Host=openk9.io"
            - "traefik.http.routers.index-writer.middlewares=index-writer-strip@docker,index-writer_compress@docker,openk9-forwarded-host@docker"

