version: "3.5"
services:
    ingestion:
        image: openk9-ingestion:latest
        container_name: openk9-ingestion
        command: sh -c "/wait && cp -a /opt/apache-karaf/configs/. /opt/apache-karaf/etc && karaf run debug"
        environment:
            WAIT_HOSTS: rabbitmq:5672
            WAIT_HOSTS_TIMEOUT: 300
            JAVA_DEBUG_PORT: '*:5005'
        volumes:
            - ./ingestion/configs:/opt/apache-karaf/configs
        expose:
            - "1099"
            - "8080"
            - "44444"
            - "8101"
            - "8181"
            - "5005"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.ingestion-docker.loadbalancer.server.port=8080"
            - "traefik.http.middlewares.ingestion-strip.stripprefix.prefixes=/ingestion"
            - "traefik.http.routers.ingestion.entrypoints=web"
            - "traefik.http.routers.ingestion.rule=PathPrefix(`/ingestion`)"
            - "traefik.http.middlewares.ingestion_compress.compress=true"
            - "traefik.http.middlewares.openk9-forwarded-host.headers.customrequestheaders.X-Forwarded-Host=openk9.io"
            - "traefik.http.routers.ingestion.middlewares=ingestion-strip@docker,ingestion_compress@docker,openk9-forwarded-host@docker"

