version: "3.5"
services:
    entity-manager:
        image: openk9-entity-manager:latest
        container_name: openk9-entity-manager
        command: sh -c "/wait && cp -a /opt/apache-karaf/configs/. /opt/apache-karaf/etc && karaf run debug"
        environment:
            WAIT_HOSTS: rabbitmq:5672, neo4j:7687
            WAIT_HOSTS_TIMEOUT: 300
            JAVA_DEBUG_PORT: '*:5005'
        volumes:
            - ./entity-manager/configs:/opt/apache-karaf/configs
        expose:
            - "1099"
            - "8080"
            - "44444"
            - "8101"
            - "8181"
            - "5005"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.entity-manager-docker.loadbalancer.server.port=8080"
            - "traefik.http.middlewares.entity-manager-strip.stripprefix.prefixes=/entity-manager"
            - "traefik.http.routers.entity-manager.entrypoints=web"
            - "traefik.http.routers.entity-manager.rule=PathPrefix(`/entity-manager`)"
            - "traefik.http.middlewares.entity-manager_compress.compress=true"
            - "traefik.http.middlewares.openk9-forwarded-host.headers.customrequestheaders.X-Forwarded-Host=openk9.io"
            - "traefik.http.routers.entity-manager.middlewares=entity-manager-strip@docker,entity-manager_compress@docker,openk9-forwarded-host@docker"
    neo4j:
        image: neo4j:latest
        container_name: neo4j
        hostname: neo4j
        environment:
            - NEO4J_AUTH=neo4j/openk9
            - NEO4JLABS_PLUGINS=["apoc"]
        volumes:
            - ./neo4j/data:/data
        ports:
            - '7474:7474'
            - '7687:7687'