version: "3.5"
services:
    reverse-proxy:
        image: traefik:v2.3
        command: --api.insecure=true --providers.docker --providers.docker.exposedbydefault=false --entrypoints.web.address=:80
        networks:
            default:
                aliases:
                    - openk9.io
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - '8888:80'
            - '8182:8080'