version: "3.9"

services:
  gitlab-parser:
    image: gitlab-parser:latest
    container_name: gitlab-parser
    environment:
      INGESTION_URL: "http://ingestion:8080/api/ingestion/v1/ingestion/"
    ports:
      - "5000:5000"
