version: '2'
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: openk9
            RABBITMQ_DEFAULT_PASS: openk9
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - amqp-quickstart-network
        volumes:
            - ./rabbitmq/data:/etc/rabbitmq/
    processor:
        build:
            dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-native-distroless}
            context: .
        environment:
            AMQP_HOST: rabbitmq
            AMQP_PASSWORD: openk9
            AMQP_USERNAME: openk9
            AMQP_PORT: 5672
            QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgres/openk9
            QUARKUS_DATASOURCE_USERNAME: openk9
            QUARKUS_DATASOURCE_PASSWORD: openk9
            QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: none
        ports:
            - "8080:8080"
        networks:
            - amqp-quickstart-network
    postgres:
        image: postgres:latest
        container_name: postgres
        hostname: postgres
        environment:
            - POSTGRES_PASSWORD=openk9
            - POSTGRES_USER=openk9
            - POSTGRES_DB=openk9
        networks:
            - amqp-quickstart-network
        ports:
            - "5432:5432"

networks:
    amqp-quickstart-network:
        name: amqp-quickstart