# Copyright Smc Treviso, S.r.l All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

# Default values for openk9-tenant-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @param replicaCount Number of Tenant Ui replicas to deploy
##
replicaCount: 1

## @section Tenant Ui Image parameters
## Docker Tenant Ui image version
## ref: https://hub.docker.com/u/smclab
## @param image.registry [default: REGISTRY_NAME] Tenant Ui image registry
## @skip image.tag Tenant Ui image tag (immutable tags are recommended)
## @param image.pullPolicy Tenant Ui image pull policy
## @param image.pullSecrets Specify docker-registry secret names as an array
image:
  registry: ""
  name: smclab/openk9-tenant-ui
  # Overrides the image tag whose default is the chart appVersion.
  ## Overrides the image tag whose default is the chart appVersion.
  tag: ""

  ## Specify a imagePullPolicy
  ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
  ##
  pullPolicy: Always

  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## Example:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets:
    - docker-registry-secret

## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations:

## @param nameOverride String to partially override fullname template (will maintain the release name)
##
nameOverride: ""

## @param fullnameOverride String to fully override fullname template
##
fullnameOverride: ""

## Kubernetes service type
##
service:
  ## @param service.type Kubernetes Service type
  ##
  type: ClusterIP
  ## Service ports
  ## @param service.port Http service port
  port: 8080

## Tenant Ui pods ServiceAccount
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  ## @param serviceAccount.create Enable creation of ServiceAccount for Tenant Ui pods
  ##
  create: false
  ## @param serviceAccount.annotations Annotations for service account. Evaluated as a template. Only used if `create` is `true`.
  ##
  annotations: {}
  ## @param serviceAccount.name Name of the created serviceAccount
  ## If not set and create is true, a name is generated using the fullname template
  ##
  name: ""


## @param podAnnotations Tenant Ui Pod annotations. Evaluated as a template
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## Tenant Ui pods' Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param podSecurityContext.enabled Enable Tenant Ui pods' Security Context
## @param podSecurityContext.fsGroupChangePolicy Set filesystem group change policy
## @param podSecurityContext.sysctls Set kernel settings using the sysctl interface
## @param podSecurityContext.supplementalGroups Set filesystem extra groups
## @param podSecurityContext.fsGroup Set Tenant Ui pod's Security Context fsGroup
##
podSecurityContext: {}
  # fsGroup: 2000


securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


## @param hostAliases Deployment pod host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []


## Configure the ingress resource that allows you to access the
## Tenant Ui installation. Set up the URL
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  ## @param ingress.enabled Enable ingress resource for Tenant Ui console
  ##
  enabled: false
  ## @param ingress.enabled Enable ingress resource for Tenant Ui console
  ##
  host: tenant-manager.local   #-TBMD
  ## @param ingress.annotations Additional annotations for the Ingress resource.
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md
  ##
  ## e.g:
  ## annotations:
  ##   kubernetes.io/ingress.class: nginx
  ##
  annotations: {}
  ## @param ingress.servicePort Path for the default port.
  ##
  servicePort: 8080
  ## @param ingress.paths Paths for the default host.
  ##
  paths:
    - /admin
  ## @param ingress.tls Enable TLS configuration for the host defined at `ingress.host` parameter
  ##
  tls:
    enabled: false
    secretName: openk9-tls-star-secret   #-TBMD

# In OpenShift use Route instead of Ingress
route:
  enabled: false
  annotations: {}
  host: tenant-manager.local 
  tls:
    enabled: false
    secretName: openk9-tls-star-secret


## @param resources Set container requests and limits for different resources like CPU or memory (essential for production workloads)
## Example:
## resources:
##   requests:
##     cpu: 2
##     memory: 512Mi
##   limits:
##     cpu: 3
##     memory: 1024Mi
##
resources:
  requests:
    cpu: 100m
    memory: 256Mi

    
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  averageCpuUtilizationPercentage: 80
  averageMemoryUtilizationPercentage: 80

## @param nodeSelector Node labels for pod assignment. Evaluated as a template
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
##
nodeSelector: {}

## @param tolerations Tolerations for pod assignment. Evaluated as a template
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## @param affinity Affinity for pod assignment. Evaluated as a template
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
##
affinity: {}

## Configure Tenant Ui containers' extra options for startup probe
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
## @param startupProbe.enabled Enable startupProbe
## @param startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
## @param startupProbe.periodSeconds Period seconds for startupProbe
## @param startupProbe.timeoutSeconds Timeout seconds for startupProbe
## @param startupProbe.failureThreshold Failure threshold for startupProbe
## @param startupProbe.successThreshold Success threshold for startupProbe
##
startupProbe:
  enabled: false
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

## Configure Tenant Ui containers' extra options for liveness probe
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
## @param livenessProbe.enabled Enable livenessProbe
## @param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
## @param livenessProbe.periodSeconds Period seconds for livenessProbe
## @param livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
## @param livenessProbe.failureThreshold Failure threshold for livenessProbe
## @param livenessProbe.successThreshold Success threshold for livenessProbe
##
livenessProbe:
  enabled: false
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

## Configure Tenant Ui containers' extra options for readiness probe
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
## @param readinessProbe.enabled Enable readinessProbe
## @param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
## @param readinessProbe.periodSeconds Period seconds for readinessProbe
## @param readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
## @param readinessProbe.failureThreshold Failure threshold for readinessProbe
## @param readinessProbe.successThreshold Success threshold for readinessProbe
##
readinessProbe:
  enabled: false
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5


