apiVersion: v1
kind: Service
metadata:
  namespace: k9-staging
  name: web-parser
  labels:
    app: web-parser
spec:
  ports:
  - name: http
    port: 5008
    targetPort: 80
  - name: admin
    port: 6800
    targetPort: 6800
  selector:
    app: web-parser
  type: LoadBalancer


---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k9-staging
  name: web-parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-parser
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-parser
    spec:
      containers:
        - name: web-parser
          image: registry.smc.it:49083/openk9/web-parser:0.0.1
          ports:
            - containerPort: 6800
            - containerPort: 80
          env:
            - name: INGESTION_URL
              value: http://ingestion:8080/v1/ingestion/
      imagePullSecrets:
        - name: registry.smc.it