variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

Build Latest Ingestion Docker Images:
    image: smclab/docker-java-11:latest
    services:
        - docker:19.03.13-dind
    stage: build-docker
    before_script:
        - export GRADLE_USER_HOME=`pwd`/.gradle
    variables:
        TEST_NAME: local/test
        DOCKER_HOST: tcp://localhost:2375
        DOCKER_TLS_CERTDIR: ""
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
          changes:
              - quarkus/ingestion/**/*
              - quarkus/ingestion/*
              - .gitlab/.gitlab-ci-ingestion.yml
              - gradle.properties
    script:
        - ./gradlew build -p ./quarkus/ingestion -Dquarkus.package.type=mutable-jar -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=latest
    after_script:
        - curl -X POST -F token=$DEV_TOKEN -F "variables[TRIGGER_JOB]=deploy-ingestion" -F ref=master $DEV_TRIGGER_URL
    cache:
        key: build-docker-cache
        untracked: true
        paths:
            - $CI_PROJECT_DIR/.m2/**/*
            - .gradle/caches
            - .gradle/wrapper
        policy: push
cache:
    key: build-docker-cache
    untracked: true
    paths:
        - $CI_PROJECT_DIR/.m2/**/*
        - .gradle/wrapper
        - .gradle/caches
    policy: pull
