Build Tagged Datasource Docker Images:
  image: eclipse-temurin:17-jdk
  services:
    - docker:19.03.13-dind
  stage: build-docker
  variables:
    TEST_NAME: local/test
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  only:
    refs:
      - tags
    changes:
      - core/app/datasource/ci.properties
  except:
    - schedules
  script:
    - cd core
    - ./mvnw package $MAVEN_CLI_OPTS -pl ../vendor/hibernate-rx-multitenancy/deployment,app/datasource -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
  cache:
    key: datasource
    paths:
      - .m2/repository

Build Latest Datasource Docker Images:
  image: eclipse-temurin:17-jdk
  services:
    - docker:19.03.13-dind
  stage: build-docker
  variables:
    TEST_NAME: local/test
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  only:
    refs:
      - main
  when:
    manual
  script:
    - cd core
    - ./mvnw package $MAVEN_CLI_OPTS -pl ../vendor/hibernate-rx-multitenancy/deployment,app/datasource -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
  cache:
    key: datasource
    paths:
      - .m2/repository

Build Datasource [DEV]:
  image: eclipse-temurin:17-jdk
  services:
    - docker:19.03.13-dind
  stage: build-docker
  variables:
    TEST_NAME: local/test
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  only:
    refs:
      - /^\d+-.+$/
  when:
    manual
  script:
    - cd core
    - ./mvnw package $MAVEN_CLI_OPTS -pl ../vendor/hibernate-rx-multitenancy/deployment,app/datasource -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=999-SNAPSHOT
  cache:
    key: datasource
    paths:
      - .m2/repository

trigger_deploy_datasource:
  image: curlimages/curl
  stage: deploy
  needs: ['Build Latest Datasource Docker Images']
  only:
    refs:
      - main
    changes:
      - core/app/datasource/ci.properties
  except:
    - schedules
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - curl -X POST -F token=$DEPLOY_TOKEN -F "variables[TRIGGER_JOB]=deploy-datasource" -F ref=master $DEPLOY_TRIGGER_URL

trigger_restart_datasource:
  image: curlimages/curl
  stage: deploy
  needs: [ 'Build Datasource [DEV]' ]
  only:
    refs:
      - /^\d+-.+$/
  when:
    manual
  except:
    - schedules
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - curl -X POST -F token=$RESTART_TRIGGER_TOKEN -F "variables[TRIGGER_JOB]=restart-datasource" -F ref=master $RESTART_TRIGGER_URL
