Build Branch File Manager Docker Images:
  image: smclab/docker-java-11:latest
  services:
    - docker:19.03.13-dind
  stage: build-docker
  variables:
    TEST_NAME: local/test
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  only:
    refs:
      - main
      - tags
    changes:
      - core/app/common/resources-common/**/*
      - core/app/common/resources-common/pom.xml
      - core/app/file-manager/**/*
      - core/app/pom.xml
  except:
    - schedules
  script:
    - cd core
    - ./mvnw package $MAVEN_CLI_OPTS -pl app/file-manager -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
  cache:
    key: file-manager
    paths:
      - .m2/repository
