################################################################################
#                           STAGES, VARIABLES & INCLUDE                         #
################################################################################

stages:
- build
- container-scanning
- restart

variables:
  CS_ANALYZER_IMAGE: "$CI_TEMPLATE_REGISTRY_HOST/security-products/container-scanning:7"

include:
- local: '/.gitlab/.gitlab-templates.yaml'

################################################################################
#                                   JOBS                                        #
################################################################################

######################## BUILD INGESTION IMAGE ########################
Build Ingestion image:
  extends: .build_template
  variables:
    COMPONENT: "ingestion"
  stage: build
  script:
  - cd core
  - |
    # Extract the version from pom.xml and set it as an environment variable
    VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    echo "VERSION=$VERSION"
    echo "$VERSION" > $CI_PROJECT_DIR/.version
  - |
    if [[ "$CI_COMMIT_BRANCH" == "main" || $CI_COMMIT_TAG != "" ]]; then
      mvn package $MAVEN_OPTS -pl app/ingestion -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
    elif [[ "$CI_PIPELINE_SOURCE" == "merge_request_event" ]]; then
      mvn package $MAVEN_OPTS -pl app/ingestion -am -Dquarkus.container-image.build=false -Dquarkus.container-image.push=false
    elif [[ "$CI_COMMIT_BRANCH" =~ ^[0-9]+-.*$ && "$GITLAB_USER_LOGIN" == "michele.bastianelli" ]]; then
      mvn package $MAVEN_OPTS -pl app/ingestion -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=998-SNAPSHOT -P 'exclude-quarkus-test'
    elif [[ "$CI_COMMIT_BRANCH" =~ ^[0-9]+-.*$ && "$GITLAB_USER_LOGIN" == "mirko.zizzari" ]]; then
      mvn package $MAVEN_OPTS -pl app/ingestion -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=999-SNAPSHOT -P 'exclude-quarkus-test'
    elif [[ "$CI_COMMIT_BRANCH" =~ ^[0-9]+-.*$ ]]; then
      mvn package $MAVEN_OPTS -pl app/ingestion -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=999-SNAPSHOT -P 'exclude-quarkus-test'
    fi
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
  # Case 1: When there is a commit to main (push to main)
  - if: '$CI_COMMIT_BRANCH == "main"'
  # Case 2: When a merge request is approved
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  # Case 3: When a tag is created
  - if: '$CI_COMMIT_TAG'
  # Block the first execution when a branch is created
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'
    when: never
  # Case 4: When the commit is made on a feature branch that matches the pattern ^[0-9]+-.*$
  - if: '$CI_COMMIT_BRANCH =~ /^([0-9]+-.*)$/'

###################### CONTAINER SCANNING INGESTION ######################
Container Scanning Ingestion:
  dependencies: [ Build Ingestion image ]
  extends: .container-scanning-template
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-ingestion"
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
  - if: '$CI_COMMIT_TAG'

######################### TRIGGER RESTART INGESTION ######################
Trigger Restart Ingestion:
  extends: .restart_job_template
  dependencies:
  - Build Ingestion image
  variables:
    COMPONENT_NAME: "ingestion"
    COMPONENT_TYPE: "backend"
