Build Tagged K8s Client Docker Images:
  image: eclipse-temurin:17-jdk
  services:
    - docker:19.03.13-dind
  stage: build-docker
  variables:
    TEST_NAME: local/test
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  only:
    refs:
      - tags
    changes:
      - core/app/k8s-client/ci.properties
  except:
    - schedules
  script:
    - cd core
    - ./mvnw package $MAVEN_CLI_OPTS -pl app/k8s-client -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
  cache:
    key: k8s-client
    paths:
      - .m2/repository

Build Latest K8s Client Docker Images:
  image: eclipse-temurin:17-jdk
  services:
    - docker:19.03.13-dind
  stage: build-docker
  variables:
    TEST_NAME: local/test
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  only:
    refs:
      - main
  when:
    manual
  except:
    - schedules
  script:
    - cd core
    - ./mvnw package $MAVEN_CLI_OPTS -pl app/k8s-client -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
  cache:
    key: k8s-client
    paths:
      - .m2/repository

Build K8s Client [DEV]:
  image: eclipse-temurin:17-jdk
  services:
    - docker:19.03.13-dind
  stage: build-docker
  variables:
    TEST_NAME: local/test
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  only:
    refs:
      - /^\d+-.+$/
  when:
    manual
  except:
    - schedules
  script:
    - cd core
    - ./mvnw package $MAVEN_CLI_OPTS -pl app/k8s-client -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=999-SNAPSHOT
  cache:
    key: k8s-client
    paths:
      - .m2/repository

trigger_deploy_k8s_client:
  image: curlimages/curl
  stage: deploy
  needs: ['Build Latest Ingestion Docker Images']
  only:
    refs:
      - main
    changes:
      - core/app/k8s-client/ci.properties
  except:
    - schedules
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - curl -X POST -F token=$DEPLOY_TOKEN -F "variables[TRIGGER_JOB]=deploy-k8s-client" -F ref=master $DEPLOY_TRIGGER_URL

argocd-restart:
  image: argoproj/argocd
  stage: deploy
  needs: [ 'Build K8s Client [DEV]' ]
  variables:
    GIT_STRATEGY: none
    ARGOCD_SERVER: "argocd.openk9.io"
    ARGOCD_APP_NAME: "k8s-client"
  before_script:
    - echo "ARGOCD_SERVER:$ARGOCD_SERVER"
    - echo "ARGOCD_APP_NAME:$ARGOCD_APP_NAME"
    - echo "ARGOCD_USERNAME:$ARGOCD_USERNAME"
  script:
    - argocd login "${ARGOCD_SERVER}" --username "${ARGOCD_USERNAME}" --password "${ARGOCD_PASSWORD}"
    - argocd app actions run "$ARGOCD_APP_NAME" restart --kind Deployment |& tee response.txt
    - cat response.txt
    # if response.txt have content, exit with error, empty response means success
    - if [ -s response.txt ]; then exit 1; fi
  only:
    refs:
      - /^\d+-.+$/