variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

Build Latest Index Writer Docker Images:
  image: smclab/docker-java-11:latest
  services:
    - docker:19.03.13-dind
  stage: build-docker
  variables:
    TEST_NAME: local/test
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  only:
    refs:
      - main
    changes:
      - index-writer/configs/*
      - osgi/index-writer/**/*
      - osgi/search/search-client-api/**/*
      - osgi/search/search-client-service/**/*
      - osgi/search/search-client-metrics/**/*
      - osgi/search/search-client-writer/**/*
      - osgi/metrics/metrics-api/**/*
      - osgi/metrics/metrics-service/**/*
      - osgi/metrics/metrics-ext/**/*
      - osgi/common/common-api/**/*
      - osgi/common/core-api/**/*
      - osgi/common/model/**/*
      - osgi/common/osgi-api/**/*
      - osgi/common/serialization-api/**/*
      - osgi/common/serialization-service/**/*
      - osgi/third-party/reactor/**/*
      - osgi/third-party/reactor-netty/**/*
      - osgi/third-party/reactive-streams/**/*
      - osgi/third-party/micrometer/**/*
      - osgi/third-party/jackson/**/*
      - osgi/third-party/vavr/**/*
      - osgi/third-party/apache/**/*
      - osgi/common/http-serialization/**/*
      - osgi/ingestion/ingestion-api/**/*
      - osgi/ingestion/ingestion-service/**/*
      - osgi/common/reactory-netty-util/**/*
      - osgi/web/http-api/**/*
      - osgi/web/http-service/**/*
      - osgi/web/http-bundle-ext/**/*
      - osgi/web/open-api/**/*
      - osgi/datasource/datasource-client-api/**/*
      - osgi/datasource/datasource-client-service/**/*
      - osgi/plugin-driver-manager/plugin-driver-manager-client-api/**/*
      - osgi/plugin-driver-manager/plugin-driver-manager-client-service/**/*
      - osgi/plugin-driver-manager/plugin-driver-manager-model/**/*
      - osgi/vertx/**/*
      - .gitlab/.gitlab-ci-index-writer.yml
  except:
    - schedules
  script:
    - ./gradlew --build-cache --gradle-user-home cache/ pushImageIndexWriter
  after_script:
    - curl -X POST -F token=$DEV_TOKEN -F "variables[TRIGGER_JOB]=deploy-index-writer" -F ref=master $DEV_TRIGGER_URL
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
        - $CI_PROJECT_DIR/config/index-writer/cache.lock
    paths:
      - cache/caches/
      - cache/notifications/
      - cache/wrapper/