################################################################################
#                                   STAGES                                     #
################################################################################
stages:
  - build
  - build-verifier
  - container-scanning
  - dependency-check
  - restart
  - publish


include:
  - local: '/.gitlab/.gitlab-templates.yaml'

################################################################################
#                                  JOBS                                        #
################################################################################

#################
# Fetch Version #
#################
Fetch version: 
  stage: build
  image: node:16-alpine
  script:
    - cd js-packages/search-frontend
    - export VERSION=$(node -p "require('./package.json').version") # Legge la versione dal package.json
    - echo "VERSION=$VERSION" > $CI_PROJECT_DIR/version.env # Salva la versione in un file
  artifacts:
    paths:
      - version.env
    expire_in: 1 day

######################## BUILD SEARCH FRONTEND ########################
Build Search Frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    DOCKER_CONFIG: "/kaniko/.docker"
  needs:
    - job: Fetch version
      artifacts: true
  script:
    - source $CI_PROJECT_DIR/version.env # Carica la versione dall'artifact
    - echo "=== Using VERSION=$VERSION ==="
    - echo "=== Configurazione credenziali Kaniko ==="
    - export NODE_OPTIONS="--max-old-space-size=4096" # Aumenta la memoria massima per Node

    - mkdir -p /kaniko/.docker
    - |
      echo "{\"auths\":{\"$CI_REGISTRY_NAME\":{\"auth\":\"$(printf "%s:%s" \ 
      "${CI_REGISTRY_USERNAME}" "${CI_REGISTRY_PASSWORD}" \
      | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json 
    - |
      /kaniko/executor \
        --context "${CI_PROJECT_DIR}" \
        --dockerfile "${CI_PROJECT_DIR}/js-packages/search-frontend/Dockerfile" \
        --destination "$CI_REGISTRY_NAME/openk9/search-frontend:$VERSION"
  rules:
    - changes:
        - js-packages/search-frontend/**/*
    - if: '$CI_COMMIT_BRANCH == "main"'

######################## BUILD VERIFIER (NODE) ########################
Build Verifier:
  stage: build-verifier
  image: node:14
  script:
    - cd js-packages/search-frontend
    - yarn install
    - yarn build
  rules:
    - changes:
        - js-packages/search-frontend/**/*
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

######################## CONTAINER SCANNING ########################
Container Scanning:
  stage: container-scanning
  image: $CI_TEMPLATE_REGISTRY_HOST/security-products/container-scanning:latest
  dependencies:
    - "Build Search Frontend"
  script:
    - source version.env # Carica la versione dall'artifact
    - echo "Scanning image $CI_REGISTRY_NAME/openk9/search-frontend:$VERSION" 
    - container-scanning scan --image "$CI_REGISTRY_NAME/openk9/search-frontend:$VERSION"  # Esegue lo scan dell'immagine
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

######################## TRIGGER RESTART ########################
Trigger Restart:
  stage: restart
  image: alpine:latest
  script:
    - apk add --no-cache curl
    - echo "Triggering restart for Search Frontend"
      # Invia una richiesta POST al trigger URL per far partire il job `restart-admin-frontend`
    - |
      curl -X POST \
        -F "token=${RESTART_TRIGGER_TOKEN}" \
        -F "variables[TRIGGER_JOB]=restart-admin-frontend" \
        -F "ref=main" \
        "${RESTART_TRIGGER_URL}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

####################### PUBLISH SEARCH FRONTEND #######################
Publish Search Frontend:
  stage: publish
  image: node:16
  script:
    - cd js-packages/search-frontend
    - pwd
    - whoami
    - yarn install
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
    - npm publish --access public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - when: never


####################### DEPENDENCY CHECK #######################
Dependency Check Search Frontend:
  stage: dependency-check
  extends: .dependency_check_frontend_template
  allow_failure: true
  script:
    - cd js-packages/search-frontend
    - /analyzer run



