variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

Build Latest Plugin Driver Manager Docker Images:
  image: smclab/docker-java-11:latest
  services:
    - docker:19.03.13-dind
  stage: build-docker
  variables:
    TEST_NAME: local/test
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  only:
    refs:
      - main
    changes:
      - plugin-driver-manager/configs/*
      - osgi/common/reactory-netty-util/**/*
      - osgi/web/http-api/**/*
      - osgi/web/http-service/**/*
      - osgi/web/http-bundle-ext/**/*
      - osgi/web/open-api/**/*
      - osgi/metrics/metrics-api/**/*
      - osgi/metrics/metrics-service/**/*
      - osgi/common/common-api/**/*
      - osgi/common/core-api/**/*
      - osgi/common/model/**/*
      - osgi/common/osgi-api/**/*
      - osgi/common/serialization-api/**/*
      - osgi/common/serialization-service/**/*
      - osgi/third-party/reactor/**/*
      - osgi/third-party/reactor-netty/**/*
      - osgi/third-party/reactive-streams/**/*
      - osgi/third-party/micrometer/**/*
      - osgi/third-party/jackson/**/*
      - osgi/third-party/vavr/**/*
      - osgi/third-party/apache/**/*
      - osgi/common/http-serialization/**/*
      - osgi/index-writer/index-writer-model/**/*
      - osgi/index-writer/index-writer-mappings-publisher-api/**/*
      - osgi/index-writer/index-writer-mappings-publisher-service/**/*
      - osgi/index-writer/index-writer-mappings-pub-sub/**/*
      - osgi/plugin-driver-manager/**/*
      - osgi/search/search-enrich-service/**/*
      - osgi/search/search-enrich-api/**/*
      - osgi/plugin/plugin-api/**/*
      - osgi/plugin/plugin-service/**/*
      - osgi/plugin/plugin-web/**/*
      - osgi/ingestion/**/*
      - plugins/email/**/*
      - plugins/liferay/**/*
      - plugins/web/**/*
      - plugins/applications/**/*
      - plugins/js-enrich-plugin/**/*
      - osgi/entity-manager/**/*
      - osgi/vertx/**/*
      - .gitlab/.gitlab-ci-plugin-driver-manager.yml
  except:
    - schedules
  script:
    - ./gradlew --build-cache --gradle-user-home cache/ pushImagePluginDriverManager
  after_script:
    - curl -X POST -F token=$DEV_TOKEN -F "variables[TRIGGER_JOB]=deploy-plugin-driver-manager" -F ref=master $DEV_TRIGGER_URL
  cache:
    key: plugin-driver-manager
    paths:
      - cache/caches/
      - cache/notifications/
      - cache/wrapper/