Build Latest Tenant Ui Docker Image:
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  stage: build-image
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 0
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  only:
    refs:
      - main
    changes:
      - .gitlab/.gitlab-ci-tenant-frontend.yml
      - js-packages/tenant-ui/**/*
  except:
    - schedules
  before_script:
    - sleep 5
    - docker login -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_NAME
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - docker build -t openk9-tenant-ui:latest -f js-packages/tenant-ui/Dockerfile .
    - docker tag openk9-tenant-ui:latest $CI_REGISTRY_NAME/openk9/openk9-tenant-ui:latest
    - docker push $CI_REGISTRY_NAME/openk9/openk9-tenant-ui:latest


Build Tagged Tenant Ui Docker Image:
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  stage: build-image
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  only:
    refs:
      - tags
    changes:
      - .gitlab/.gitlab-ci-tenant-frontend.yml
      - js-packages/tenant-ui/**/*
  except:
    - schedules
  before_script:
    - docker login -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_NAME
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - docker build -t tenant-ui:${CI_COMMIT_REF_NAME} -f js-packages/tenant-ui/Dockerfile .
    - docker tag tenant-ui:${CI_COMMIT_REF_NAME} $CI_REGISTRY_NAME/openk9/tenant-ui:${CI_COMMIT_REF_NAME}
    - docker push $CI_REGISTRY_NAME/openk9/tenant-ui:${CI_COMMIT_REF_NAME}