stages:
  - build
  - container-scanning
  - restart
  - quality
  - build-verifier


# Build Docker Image
Build Admin Frontend:
  stage: build
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind

  before_script:
    - docker login -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/admin-frontend:latest -f js-packages/admin-ui/Dockerfile .
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        docker push $CI_REGISTRY/admin-frontend:latest
      fi
  rules:
    #- changes:
    #    - js-packages/admin-ui/**/*
    - when: never

# Container Scanning (se non funge, comparare con search-frontend)
Container Scanning:
  stage: container-scanning
  extends: .container-scanning-template
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# Trigger Restart
Trigger Restart:
  stage: restart
  image: alpine:latest
  script:
    - apk add --no-cache curl
    - echo "Triggering restart for Admin Frontend"
    - |
      curl -X POST \
        -F "token=${RESTART_TRIGGER_TOKEN}" \
        -F "variables[TRIGGER_JOB]=restart-admin-frontend" \
        -F "ref=main" \
        "${RESTART_TRIGGER_URL}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# Build Verifier
Build Verifier:
  stage: build-verifier
  #immagine con node/npm per provare yarn install e build
  image: node:14
  script:
    - cd js-packages/admin-ui
    - yarn install
    - yarn build
  rules:
    - changes:
        - js-packages/admin-ui/**/*
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'