################################################################################
#                           STAGES, VARIABLES & INCLUDE                         #
################################################################################

stages:
  - build
  - container-scanning
  - restart

variables:
  CS_ANALYZER_IMAGE: "$CI_TEMPLATE_REGISTRY_HOST/security-products/container-scanning:7"

include:
  - local: '/.gitlab/.gitlab-templates.yaml'

################################################################################
#                                   JOBS                                        #
################################################################################

######################## BUILD TIKA NO-OCR IMAGE ########################
Build Tika no-ocr:
  extends: .build_template
  variables:
    COMPONENT: "tika-no-ocr"
  stage: build
  script:
    - cd core
    - |
    # Extract version from pom.xml and set it as environment variable
      VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      echo "VERSION=$VERSION"
      echo "$VERSION" > $CI_PROJECT_DIR/.version
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" || $CI_COMMIT_TAG != "" ]]; then
        mvn package $MAVEN_OPTS -pl app/tika/tika-no-ocr -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
      elif [[ "$CI_PIPELINE_SOURCE" == "merge_request_event" ]]; then
      mvn package $MAVEN_OPTS -pl app/tika/tika-no-ocr -am -Dquarkus.container-image.build=false -Dquarkus.container-image.push=false
      elif [[ "$CI_COMMIT_BRANCH" =~ ^[0-9]+-.*$ ]]; then
        mvn package $MAVEN_OPTS -pl app/tika/tika-no-ocr -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=999-SNAPSHOT -P 'exclude-quarkus-test'
      fi
  artifacts:
    paths:
      - .version
    expire_in: 24 hours
  rules:
  # Case 1: commit on main
    - if: '$CI_COMMIT_BRANCH == "main"'
  # Case 2: merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  # Case 3: tag creation
    - if: '$CI_COMMIT_TAG'
  # Block FIRST execution when a branch is created
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'
      when: never
  # Case 4: commit on feature branch with pattern ^[0-9]+-.*$
    - if: '$CI_COMMIT_BRANCH =~ /^([0-9]+-.*)$/'

###################### CONTAINER SCANNING TIKA NO-OCR #####################
Container Scanning Tika no-ocr:
  dependencies: [ Build Tika no-ocr ]
  extends: .container-scanning-template
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-tika-no-ocr"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'

###################### TRIGGER RESTART TIKA NO-OCR #######################
Trigger Restart Tika no-ocr:
  extends: .restart_job_template
  dependencies:
  - Build Tika no-ocr
  variables:
    COMPONENT_NAME: "tika-no-ocr"
    COMPONENT_TYPE: "backend"
