################################################################################
#                           STAGES, VARIABLES & INCLUDE                         #
################################################################################

stages:
  - build
  - container-scanning
  - restart

variables:
  CS_ANALYZER_IMAGE: "$CI_TEMPLATE_REGISTRY_HOST/security-products/container-scanning:7"

include:
  - local: '/.gitlab/.gitlab-templates.yaml'


################################################################################
#                                   JOBS                                        #
################################################################################

######################## BUILD K8S-CLIENT IMAGE ########################
Build K8S-Client image:
  extends: .build_template
  variables:
    COMPONENT: "k8s-client"
  stage: build
  script:
    - cd core
    - |
      VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      echo "VERSION=$VERSION"
      echo "$VERSION" > $CI_PROJECT_DIR/.version
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" || $CI_COMMIT_TAG != "" ]]; then
        mvn package $MAVEN_OPTS -pl app/k8s-client -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
      elif [[ "$CI_MERGE_REQUEST_ID" ]]; then
        mvn package $MAVEN_OPTS -pl app/entity-manager -am -Dquarkus.container-image.build=false -Dquarkus.container-image.push=false
      elif [[ "$CI_COMMIT_BRANCH" =~ ^[0-9]+-.*$ && "$GITLAB_USER_LOGIN" == "michele.bastianelli" ]]; then
        mvn package $MAVEN_OPTS -pl app/k8s-client -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=998-SNAPSHOT -P 'exclude-quarkus-test'
      elif [[ "$CI_COMMIT_BRANCH" =~ ^[0-9]+-.*$ ]]; then
        mvn package $MAVEN_OPTS -pl app/k8s-client -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=999-SNAPSHOT -P 'exclude-quarkus-test'
      fi
  artifacts:
    paths:
      - .version
    expire_in: 24 hours
  rules:
    # Caso 1: Quando c'è un commit su main (push su main)
    - if: '$CI_COMMIT_BRANCH == "main"'
    # Caso 2: Quando viene approvata una merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # Caso 3: Quando viene creato un tag
    - if: '$CI_COMMIT_TAG'
    # Blocco della prima esecuzione quando viene creato un branch
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'
      when: never
    # Caso 4: Quando il commit è fatto su una feature branch che rispetta il pattern ^[0-9]+-.*$
    - if: '$CI_COMMIT_BRANCH =~ /^([0-9]+-.*)$/'


###################### CONTAINER SCANNING K8S-CLIENT ####################
Container Scanning K8S-Client:
  dependencies: [Build K8S-Client image]
  extends: .container-scanning-template
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-k8s-client"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'


##################### TRIGGER RESTART K8S-CLIENT ########################
Trigger Restart K8S-Client:
  image: alpine:latest
  stage: restart
  script:
    - apk add --no-cache curl
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" || "$CI_COMMIT_BRANCH" =~ ^[0-9]+-.*$ || "$CI_COMMIT_TAG" != "" ]]; then
        echo "Branch matches main or pattern"
        if [[ "$GITLAB_USER_LOGIN" == "michele.bastianelli" ]]; then
          echo "Triggering restart-k8s-client with backend version"
          curl -X POST -F token=$RESTART_TRIGGER_TOKEN -F "variables[TRIGGER_JOB]=restart-k8s-client" -F "variables[NAMESPACE]=k9-backend01" -F ref=master $RESTART_TRIGGER_URL
        else
          echo "Triggering restart-k8s-client (default)"
          curl -X POST -F token=$RESTART_TRIGGER_TOKEN -F "variables[TRIGGER_JOB]=restart-k8s-client" -F ref=master $RESTART_TRIGGER_URL
        fi
      else
        echo "Branch does not match main or pattern"
      fi
  rules:
    # Caso 1: Quando c'è un commit su main (push su main)
    - if: '$CI_COMMIT_BRANCH == "main"'
    # Caso 2: Quando viene approvata una merge request
    #- if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # Caso 3: Quando viene creato un tag
    - if: '$CI_COMMIT_TAG'
    # Blocco della prima esecuzione quando viene creato un branch
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'
      when: never
    # Caso 4: Quando il commit è fatto su una feature branch che rispetta il pattern ^[0-9]+-.*$
    - if: '$CI_COMMIT_BRANCH =~ /^([0-9]+-.*)$/'
