Build Latest Searcher Docker Images:
  image: eclipse-temurin:17-jdk
  services:
    - docker:19.03.13-dind
  stage: build-docker
  variables:
    TEST_NAME: local/test
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  only:
    refs:
      - 280-searcher-refactoring
      - tags
    changes:
      - quarkus/resources-common/**/*
      - quarkus/searcher/**/*
      - .gitlab/.gitlab-ci-searcher.yml
      - quarkus/pom.xml
  except:
    - schedules
  script:
    - ./mvnw -Psmc,quarkus package $MAVEN_CLI_OPTS -pl quarkus/searcher -am -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=280-searcher-refactoring
  after_script:
    - curl -X POST -F token=$DEV_TOKEN -F "variables[TRIGGER_JOB]=deploy-searcher" -F ref=master $DEV_TRIGGER_URL
  cache:
    key: searcher
    paths:
      - .m2/repositoryy


trigger_deploy_searcher:
  image: curlimages/curl
  stage: deploy
  needs: ['Build Latest Searcher Docker Images']
  only:
    refs:
      - main
    changes:
      - searcher/configs/*
      - osgi/common/reactory-netty-util/**/*
      - osgi/web/http-api/**/*
      - osgi/web/http-service/**/*
      - osgi/web/http-bundle-ext/**/*
      - osgi/metrics/metrics-api/**/*
      - osgi/metrics/metrics-service/**/*
      - osgi/common/common-api/**/*
      - osgi/common/core-api/**/*
      - osgi/common/model/**/*
      - osgi/common/osgi-api/**/*
      - osgi/common/serialization-api/**/*
      - osgi/common/serialization-service/**/*
      - osgi/third-party/**/*
      - osgi/common/http-serialization/**/*
      - osgi/index-writer/index-writer-model/**/*
      - osgi/search/**/*
      - osgi/datasource/datasource-client-api/**/*
      - osgi/datasource/datasource-client-service/**/*
      - osgi/auth/auth-api/**/*
      - osgi/auth/auth-service/**/*
      - osgi/auth/auth-query-parser/**/*
      - osgi/ingestion/ingestion-api/**/*
      - osgi/ingestion/ingestion-service/**/*
      - osgi/plugin-driver-manager/plugin-driver-manager-client-api/**/*
      - osgi/plugin-driver-manager/plugin-driver-manager-client-service/**/*
      - osgi/plugin-driver-manager/plugin-driver-manager-model/**/*
      - osgi/third-party/caffeine/**/*
      - osgi/vertx/**/*
      - assemblies/searcher/**/*
      - .gitlab/.gitlab-ci-searcher.yml
  except:
    - schedules
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - curl -X POST -F token=$DEPLOY_TOKEN -F "variables[TRIGGER_JOB]=deploy-searcher" -F ref=master $DEPLOY_TRIGGER_URL