Build Search Frontend Docker Image:
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  stage: build-docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  only:
    refs:
      - main
    changes:
      - js-packages/search-frontend/**/*
      - .gitlab/.gitlab-ci-search-frontend.yml
  except:
    - schedules
  before_script:
    - docker login -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_NAME
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - docker build -t search-frontend:latest -f js-packages/search-frontend/Dockerfile .
    - docker tag search-frontend:latest $CI_REGISTRY_NAME/openk9/search-frontend:latest
    - docker push $CI_REGISTRY_NAME/openk9/search-frontend:latest

Build Search Frontend Test Docker Image:
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  stage: build-docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  only:
    refs:
      - main
    changes:
      - js-packages/search-frontend/**/*
      - .gitlab/.gitlab-ci-search-frontend.yml
  except:
    - schedules
  before_script:
    - docker login -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_NAME
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - docker build -t search-frontend:latest -f js-packages/search-frontend/Dockerfile .
    - docker tag search-frontend:latest $CI_REGISTRY_NAME/openk9/search-frontend:305-refactoring-con-nuovi-endpoint-search-frontend
    - docker push $CI_REGISTRY_NAME/openk9/search-frontend:305-refactoring-con-nuovi-endpoint-search-frontend

Build Tagged Frontend Docker Image:
  image: docker:19.03.13
  services:
    - docker:19.03.13-dind
  stage: build-docker
  variables:
    TEST_NAME: local/test
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  only:
    refs:
      - tags
    changes:
      - js-packages/rest-api/**/*
      - js-packages/search-ui-components/**/*
      - js-packages/plugin-scripts/**/*
      - js-packages/search-customizable-ui/**/*
      - js-packages/search-frontend/**/*
  except:
    - schedules
  before_script:
    - docker login -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_NAME
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - docker build -t search-frontend:${CI_COMMIT_REF_NAME} -f js-packages/search-frontend/Dockerfile .
    - docker tag search-frontend:${CI_COMMIT_REF_NAME} $CI_REGISTRY_NAME/openk9/search-frontend:${CI_COMMIT_REF_NAME}
    - docker push $CI_REGISTRY_NAME/openk9/search-frontend:${CI_COMMIT_REF_NAME}

trigger_deploy_search_frontend:
  image: curlimages/curl
  stage: deploy
  needs: ['Build Search Frontend Docker Image']
  only:
    refs:
      - main
    changes:
      - js-packages/rest-api/**/*
      - js-packages/search-ui-components/**/*
      - js-packages/plugin-scripts/**/*
      - js-packages/search-customizable-ui/**/*
      - js-packages/search-frontend/**/*
  except:
    - schedules
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - curl -X POST -F token=$DEPLOY_TOKEN -F "variables[TRIGGER_JOB]=deploy-query-frontend" -F ref=master $DEPLOY_TRIGGER_URL


trigger_mvp:
  image: curlimages/curl
  stage: deploy
  only:
    refs:
      - main
    changes:
      - js-packages/rest-api/**/*
      - js-packages/search-ui-components/**/*
      - js-packages/plugin-scripts/**/*
      - js-packages/search-customizable-ui/**/*
      - js-packages/search-frontend/**/*
  except:
    - schedules
  needs: ['Build Search Frontend Docker Image']
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - curl -X POST -F token=$MVP_TOKEN -F ref=main $MVP_TRIGGER_URL