variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build osgi:
  image: gradle:6.8.2-jdk11
  stage: build
  rules:
    - changes:
      - osgi/**/*
      - plugins/**/*
      - build-dist.gradle
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export M2_HOME=`pwd`/.m2
    - echo "$GRADLE_USER_HOME"
    - echo "$M2_HOME"
  script:
    ./gradlew clean buildDist
  cache:
    key: build-cache
    paths:
      - $CI_PROJECT_DIR/.m2/**/*
      - $CI_PROJECT_DIR/.gradle/**/*
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

Build Tagged OSGI Docker Image:
  image: docker:19.03.12
  stage: build-docker
  only: 
    - tags
  needs: [build osgi]
  before_script:
    - docker login -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORD  $CI_REGISTRY_NAME
    - docker pull $CI_REGISTRY_NAME/openk9/apache-karaf:4.3.0
  script:
    - docker build -t openk9-core:latest -f osgi/Dockerfile .
    - docker tag openk9-core:latest $CI_REGISTRY_NAME/openk9/openk9-core:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_NAME/openk9/openk9-core:$CI_COMMIT_REF_NAME

Build Latest OSGI Docker Image:
  image: docker:19.03.12
  stage: build-docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      changes:
        - osgi/**/*
        - plugins/**/*
        - build-dist.gradle
  needs: [build osgi]
  before_script:
    - docker login -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORD  $CI_REGISTRY_NAME
    - docker pull $CI_REGISTRY_NAME/openk9/apache-karaf:4.3.0
  script:
    - docker build -t openk9-core:latest -f osgi/Dockerfile .
    - docker tag openk9-core:latest $CI_REGISTRY_NAME/openk9/openk9-core:latest
    - docker push $CI_REGISTRY_NAME/openk9/openk9-core:latest