variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

Build Latest Entity Manager Docker Images:
    image: smclab/docker-java-11:latest
    services:
        - docker:19.03.13-dind
    stage: build-docker
    before_script:
        - export GRADLE_USER_HOME=`pwd`/.gradle
    variables:
        TEST_NAME: local/test
        DOCKER_HOST: tcp://localhost:2375
        DOCKER_TLS_CERTDIR: ""
        JAVA_ENABLE_DEBUG: 'true'
    rules:
        - if: '$CI_COMMIT_BRANCH == "async-enrich-processor"'
          changes:
              - quarkus/entity-manager/**/*
              - .gitlab/.gitlab-ci-hazelcast-entity-manager.yml
    script:
        - ./gradlew build -p ./quarkus/entity-manager -Dquarkus.package.type=mutable-jar -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=latest -Dquarkus.log.category.\"io.openk9.entity.manager.jet.CreateEntitiesRunnable\".level=DEBUG
    after_script:
        - curl -X POST -F token=$DEV_TOKEN -F "variables[TRIGGER_JOB]=deploy-entity-manager" -F ref=master $DEV_TRIGGER_URL
    cache:
        key: build-docker-cache
        untracked: true
        paths:
            - $CI_PROJECT_DIR/.m2/**/*
            - .gradle/caches
            - .gradle/wrapper
        policy: push
cache:
    key: build-docker-cache
    untracked: true
    paths:
        - $CI_PROJECT_DIR/.m2/**/*
        - .gradle/wrapper
        - .gradle/caches
    policy: pull