apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  QUARKUS_HTTP_ACCESS_LOG_ENABLED: {{ .Values.config.httpAccessLog.enabled | quote }}
  QUARKUS_HTTP_ACCESS_LOG_PATTERN: {{ .Values.config.httpAccessLog.pattern | quote }}
  QUARKUS_LOG_LEVEL: {{ .Values.quarkus.LogLevel | quote }}
  QUARKUS_HTTP_CORS: {{ .Values.quarkus.HttpCors | quote }}
  QUARKUS_HTTP_CORS_ORIGINS: {{ .Values.quarkus.HttpCorsOrigin | quote }}
  QUARKUS_LOG_CONSOLE_JSON:  {{ .Values.quarkus.LogConsoleJson | quote }}
  
  OPENK9_KUBERNETES_CLIENT_NAMESPACE: {{ .Values.k8s.namespace | quote }}

  # OPENK9_PIPELINE_RESPONSE_URL: "http://openk9-datasource:8080/api/datasource/pipeline/callback/"
  # OPENK9_PIPELINE_BASE_IMAGE_ML: "smclab/openk9-enrich-service:latest"
  OPENK9_PIPELINE_ML_PREDICTION_TIMEOUT: {{ .Values.ml.timeout | quote }}
  OPENK9_PIPELINE_ML_PREDICTION_MAX_LENGTH: {{ .Values.ml.maxLength | quote }}

    # Keycloak env variables
  QUARKUS_OIDC_AUTH_SERVER_URL: '{{ include "helper.keycloakURL" . }}/realms/master'
  QUARKUS_OIDC_CLIENT_ID: {{ .Values.keycloak.clientId | quote }}
  QUARKUS_REST_CLIENT_KEYCLOAK_CLIENT_URL: {{ include "helper.keycloakURL" . | quote }}
  OPENK9_AUTHSERVERURL_TEMPLATE: '{{ include "helper.keycloakURL" . }}/realms/{realm}'

  QUARKUS_GRPC_CLIENTS__TENANTMANAGER__HOST: {{ include "helper.tenantManagerHost" . | quote }}

  QUARKUS_KUBERNETES_NAMESPACE: {{ .Values.quarkus.kubernetes.namespace | quote }}
  QUARKUS_KUBERNETES_INGRESS_SECRETNAME: {{ .Values.quarkus.kubernetes.secretName | quote }}
  QUARKUS_KUBERNETES_INGRESS_INGRESSCLASSNAME: {{ .Values.quarkus.kubernetes.ingressClassName | quote }}

  # JVM Memory variable
  JAVA_TOOL_OPTIONS: {{ .Values.jvm.toolOptions | quote }}

  # Opentelemetry env
  QUARKUS_OTEL_SDK_DISABLED: {{ .Values.otel.disabled | quote }}
  QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .Values.otel.endpoint | quote }}