#
# Copyright (c) 2020-present SMC Treviso s.r.l. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmcharts.helm.cattle.io
spec:
  group: helm.cattle.io
  names:
    kind: HelmChart
    plural: helmcharts
    singular: helmchart
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.jobName
          name: Job
          type: string
        - jsonPath: .spec.chart
          name: Chart
          type: string
        - jsonPath: .spec.targetNamespace
          name: TargetNamespace
          type: string
        - jsonPath: .spec.version
          name: Version
          type: string
        - jsonPath: .spec.repo
          name: Repo
          type: string
        - jsonPath: .spec.helmVersion
          name: HelmVersion
          type: string
        - jsonPath: .spec.bootstrap
          name: Bootstrap
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                authPassCredentials:
                  type: boolean
                authSecret:
                  nullable: true
                  properties:
                    name:
                      nullable: true
                      type: string
                  type: object
                backOffLimit:
                  nullable: true
                  type: integer
                bootstrap:
                  type: boolean
                chart:
                  nullable: true
                  type: string
                chartContent:
                  nullable: true
                  type: string
                createNamespace:
                  type: boolean
                dockerRegistrySecret:
                  nullable: true
                  properties:
                    name:
                      nullable: true
                      type: string
                  type: object
                failurePolicy:
                  nullable: true
                  type: string
                helmVersion:
                  nullable: true
                  type: string
                jobImage:
                  nullable: true
                  type: string
                repo:
                  nullable: true
                  type: string
                repoCA:
                  nullable: true
                  type: string
                repoCAConfigMap:
                  nullable: true
                  properties:
                    name:
                      nullable: true
                      type: string
                  type: object
                set:
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                  nullable: true
                  type: object
                targetNamespace:
                  nullable: true
                  type: string
                timeout:
                  nullable: true
                  type: string
                valuesContent:
                  nullable: true
                  type: string
                version:
                  nullable: true
                  type: string
              type: object
            status:
              properties:
                jobName:
                  nullable: true
                  type: string
              type: object
          type: object
      served: true
      storage: true