apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:

  # Rabbitmq env variables
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.username | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}

  # Quarkus env generic variables
  QUARKUS_HTTP_ACCESS_LOG_ENABLED: {{ .Values.config.httpAccessLog.enabled | quote }}
  QUARKUS_HTTP_ACCESS_LOG_PATTERN: {{ .Values.config.httpAccessLog.pattern | quote }}
  QUARKUS_HTTP_LIMITS_MAX_BODY_SIZE: {{ .Values.limit.max.size | quote }}
  QUARKUS_HTTP_CORS: {{ .Values.quarkus.HttpCors | quote }}
  QUARKUS_HTTP_CORS_ORIGINS: {{ .Values.quarkus.HttpCorsOrigin | quote }}
  QUARKUS_LOG_LEVEL: {{ .Values.quarkus.LogLevel | quote }}
  QUARKUS_LOG_CONSOLE_JSON:  {{ .Values.quarkus.LogConsoleJson | quote }}


  # Custom env variables
  QUARKUS_REST_CLIENT_FILE_MANAGER_URL: {{ include "helper.fileManagerURL" . | quote }}

  # JVM Memory variable
  JAVA_TOOL_OPTIONS: {{ .Values.jvm.toolOptions | quote }}

  # Opentelemetry env
  QUARKUS_OTEL_SDK_DISABLED: {{ .Values.otel.disabled | quote }}
  QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .Values.otel.endpoint | quote }}