version: "3.5"
services:
    minio-connector:
        image: minio-connector:latest
        ports:
            - "5000:5000"
        environment:
            - INPUT_LOG_LEVEL=INFO
    minio:
        image: minio/minio:latest
        command: server /data --console-address ":9090"
        ports:
            - "9000:9000"
            - "9090:9090"
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=minio123
        volumes:
            - ./data:/data